### ISSUE TITLE
Gentest's Shape

### ISSUE THREAD

**Issue by Moondee** [graue/gentest#12]
Hello,
imagin:
var person = gentest.types.shape({
  name: gentest.types.string,
  age: gentest.types.int
});

now say we want to make sure age is always positive so we write a property like:

function chkPresonAnge() {  
        return person.age > 0;

}
now we want check this property. HOW?

Thanks;

**Comment by graue** [comment]
If you want age to always be positive use the int.positive generator:

``` js
var personGen = gentest.types.shape({
  name: gentest.types.string,
  age: gentest.types.int.positive
});
```

**Comment by Moondee** [comment]
I know I can do that. That was not the point though. Imagine the minimum age should be 18. Then we have return person.age > 18. How we should handle this?

Thanks

**Comment by graue** [comment]
Ah, so you want to generate objects where the `age` attribute is always 18 or above? You can use int.nonNegative (generates integers from 0 and up) and apply fmap to add 18 to each number:

``` js
var adultGen = gentest.types.shape({
  name: gentest.types.string,
  age: gentest.types.fmap(function(n) { return n + 18; },
                          gentest.types.int.nonNegative)
});
```

**Comment by Moondee** [comment]
Ahaa, Thanks.
