### ISSUE TITLE
How can I run genTest?

### ISSUE THREAD

**Issue by Moondee** [graue/gentest#3]
Hey,
Could you put some info on how to run genTest? 
thanks

**Comment by graue** [comment]
There are instructions in the readme on using it with [Mocha](http://visionmedia.github.io/mocha/), which will work today if you run your tests in Node.js, but it's not a perfect integration.

Thanks for asking, hopefully there will be a better answer soon.

**Comment by graue** [comment]
There's a test runner now! With Node.js installed, you can

```
npm install -g gentest
gentest path/to/tests.js
```

and there's an almost-full example in the readme.

**Comment by Moondee** [comment]
Wonderful. Thanks. I kinda like this experimental project. It would be good to know your future plan for this project :+1:
